"""followers

Revision ID: 10702ef7e13e
Revises: 9128ef79eb6e
Create Date: 2020-05-31 20:12:15.774663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10702ef7e13e'
down_revision = '9128ef79eb6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
